export const BASE_URL = 'https://api.questspace.live'
export const BACKEND_AUTH_PATH = '/session'
export const BACKEND_AUTH_REGISTER_PATH = '/users'
export const BACKEND_AUTH_FETCH_PATH = '/session'
export const CLIENT_URL = 'questspace.live'
